language: node_js
node_js:
  - "node"
  - "10"

cache: yarn

install: yarn

cache:
     paths:
        - cache/Cypress

script:
  - 'export CYPRESS_CACHE_FOLDER=../../cache/Cypress'
  - yarn run test-no-watch
  - yarn run cypress
