name: integration-tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
          start: yarn run dev
          working-directory: setup-zilla
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: f6edcae8-98e3-4997-90a8-8f185871ff4a
